name: Total-Staging-Split
on:
  workflow_dispatch:
  repository_dispatch:
    types: [staging-complete, dispatch-receiver]
  
jobs:
  deploy:
    runs-on: macos-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.CEPH_QA_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CEPH_QA_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.CEPH_DEFAULT_REGION }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        configure_one_product:
          - sharepoint
          - python-net
          - python-java
          - family
          - jasperreports
          - java
          - net
          - cpp
          - android-java
          - reporting-services
          - nodejs-java
          - php-java
          - javascript-cpp
          - nodejs-cpp
          - nodejs-net

    steps:
      - name: Checkout theme repo
        uses: actions/checkout@main
        with:
          repository: Aspose/products.aspose.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.101.0
          extended: true
      - name: Install Node.js Dependencies
        run: npm install
      - name: Install autoprefixer
        run: npm install -D --save autoprefixer
      - name: Install postcss-cli
        run: npm install -D --save postcss-cli
      - name: Configure build environment
        env:
          CONFIGURE_ONE_PRODUCT: ${{ matrix.configure_one_product }}
        run: npm run configure
      - name: Display config.json
        run: cat /Users/runner/work/products.aspose.com-workflows/products.aspose.com-workflows/config.json
      - name: Build Total
        run: hugo --config "configs/total.toml","config.json" -c "content/total" -b "https://products-qa.aspose.com/total" --cleanDestinationDir --minify
          --templateMetrics --templateMetricsHints --enableGitInfo
      - name: Prepare public folder
        run: |
            find /Users/runner/work/products.aspose.com-workflows/products.aspose.com-workflows/public -iname 'sitemap.xml' -execdir mv -i '{}' ${{ matrix.configure_one_product }}.xml \;=
            mv /Users/runner/work/products.aspose.com-workflows/products.aspose.com-workflows/total.qa.sitemap public/sitemap.xml;
      - name: Deploy Total to S3
        run: hugo deploy --config "configs/total.toml" --maxDeletes=0 --target "staging"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CEPH_QA_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CEPH_QA_SECRET_ACCESS_KEY }}
